### ISSUE TITLE
InSAR Product Guide  Processing Options do not reference ellipsoid incidence angle 

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-docs#147]
[Processing Options](https://hyp3-docs.asf.alaska.edu/guides/insar_product_guide/#processing-options) are out of date and only reference the local incidence angle; the new ellipsoidal incidence angle is not mentioned.

The [Image Files](https://hyp3-docs.asf.alaska.edu/guides/insar_product_guide/#image-files) section of the product guide *is* up to date and discusses both the local incidence angle and the ellipsoid incidence angle.

**Comment by hjkristenson** [comment]
This was corrected in https://github.com/ASFHyP3/hyp3-docs/pull/167
