### ISSUE TITLE
Request On Demand InSAR products from ASF HyP3

### ISSUE THREAD

**Issue by irmayolii** [ASFHyP3/hyp3-docs#327]
why my "jobs = hyp3.watch(jobs)" error? the result is time out

![image](https://github.com/ASFHyP3/hyp3-docs/assets/80675405/65f7b819-1547-4329-8e0d-8d06c03d4024)

**Comment by jtherrmann** [comment]
Hi @irmayolii, the screenshot that you posted shows the `hyp3.watch` function working as expected. The function should wait for your jobs to complete or timeout after the number of seconds given by the `timeout=` keyword argument. See the [`hyp3_sdk.hyp3.HyP3.watch`](https://hyp3-docs.asf.alaska.edu/using/sdk_api/#hyp3_sdk.hyp3.HyP3.watch) documentation for more details.

Please feel free to re-open this issue and provide further details if you are still not getting the expected results.
