### ISSUE TITLE
Update admonition types

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-docs#375]
**Jira:** https://asfdaac.atlassian.net/browse/TOOL-2267

*Note: The above link is accessible only to members of ASF.*

----------------------------------------------------------------------------------------------------

@hjkristenson reported via Mattermost:

> Speaking of the docs, I notice that our "notice" boxes render differently since the mkdocs update. When we use the "important" designator, it used to render with a turquoise color and a little fire icon. Now it's blue with a pencil icon. I have a vague recollection of setting that somewhere, but I could be misremembering. The blue color is maybe okay (though it doesn't stand out from the theme coloring as well, so it doesn't draw the eye quite as much), but I don't think the pencil icon really conveys that it's an update users should take note of. Any thoughts on that? 

My reply:

> According to the [docs](https://squidfunk.github.io/mkdocs-material/reference/admonitions/), we should be using the [tip](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#+type:tip) type for the fire icon, while [note](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#+type:note) is the default fallback for unknown types as renders as a pencil icon. I'm guessing that "important" is not a recognized type, so it falls back to the default "note" type.

> We should probably go through all of our admonitions and confirm that we're using one of the recognized types.

> And we should convert "important" to "tip".

**Comment by jtherrmann** [comment]
We may want to determine whether we had created a custom "important" type, or whether it was a builtin type that was removed.

**Comment by jhkennedy** [comment]
@jtherrmann `impartant` was supported in mkdocs v6: 
https://github.com/squidfunk/mkdocs-material/blob/6.2.2/docs/reference/admonitions.md#supported-types

**Comment by jhkennedy** [comment]
It's also easy to create custom ones if we want (I'd prefer to stick to the builtin ones, however):
https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions

**Comment by hjkristenson** [comment]
I did a test using `tip`, and that rendered the same way the old `important` types, so we should be able to just change them out.
