### ISSUE TITLE
incomplete key words in docs/tutorials/hyp3_insar_stack_for_ts_analysis.ipynb 

### ISSUE THREAD

**Issue by feigl** [ASFHyP3/hyp3-docs#438]
**The following code produces an error:**
search_results = asf.geo_search(
        platform=asf.SENTINEL1,
        intersectsWith='POINT(-117.599330 35.769500)',
        start='2019-06-10',
        end='2019-07-21',
        processingLevel=asf.SLC,
        beamMode=asf.IW,
        flightDirection=asf.ASCENDING,
    )

**The following code seems to work better**
search_results = asf.geo_search(
        platform=asf.PLATFORM.SENTINEL1,
        intersectsWith='POINT(-117.599330 35.769500)',
        start='2019-06-10',
        end='2019-07-21',
        processingLevel=asf.PRODUCT_TYPE.SLC,
        beamMode=asf.BEAMMODE.IW,
        flightDirection=asf.FLIGHT_DIRECTION.ASCENDING,
    )

**Comment by forrestfwilliams** [comment]
Thanks for the issue! We've provided a fix in PR #441. Feel free to try it out!
